DOCKER: "docker://aminale/test:firstpush" # INPUT & OUTPUT PATHS
path_out: "/prj/NUM_CODEX_PLUS/Amina/CellSubmission/severityPred/output_bonn_berlin"          # path to the output directory, if it doesn't exist it will be created 
path_inp: "/prj/NUM_CODEX_PLUS/Amina/CellSubmission/severityPred/data"           # path to the directory containing the input BAM files
path_ref: "/prj/NUM_CODEX_PLUS/Amina/CellSubmission/severityPred/data/pbmc_multimodal.h5seurat"         # reference transcriptome 


# INPUTS PARAMS
training_data:               # bam files for 2 (pairewise comparison) or 3 conditions (3 way comparison)
    set14:  'bonn.h5Seurat'        # testing set 2
#     set41:  'stanford_pbmc_29.h5Seurat'        # testing set 2
#     set4:  'mgh.h5Seurat'        # testing set 2
    set1: 'berlin.h5Seurat'         

test_data:               # bam files for 2 (pairewise comparison) or 3 conditions (3 way comparison)
#     set1:  'berlin.h5Seurat'        # testing set 1
    set3:  'asan_.h5Seurat'        # testing set 2
    set4:  'stanford_pbmc_29.h5Seurat'        # testing set 2
#     set5:  'stanford_29.h5Seurat'        # testing set 2
#     set7:  'cam.h5Seurat'        # testing set 2
#     set6:  'ncl.h5Seurat'        # testing set 2
#     set8:  'ucl.h5Seurat'        # testing set 2
#     set9:  'mgh.h5Seurat'        # testing set 2
    set10: 'bonn.h5Seurat'         


# Required variables "sampleID","condition" and "batch".